/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Ashen_Cafe.view;

import com.Ashen_Cafe.database.DataBaseComputer;
import com.Ashen_Cafe.database.DataBaseTerminal;
import com.Ashen_Cafe.entity.Computer;
import com.Ashen_Cafe.Support.Message;
import com.Ashen_Cafe.Support.Validation;
import com.Ashen_Cafe.database.DataBaseProgressBar;
import com.Ashen_Cafe.entity.ProgressBar;
import com.Ashen_Cafe.entity.Terminal;

/**
 *
 * @author MaLindu DiLshan
 */
public class AddPC extends javax.swing.JFrame {

    /**
     *
     */
    public AddPC() {
        initComponents();
    }
    public void setMenu(MainMenu menu){
        this.menu=menu;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_heading = new javax.swing.JLabel();
        lbl_pcname = new javax.swing.JLabel();
        lbl_note = new javax.swing.JLabel();
        lbl_ipaddress = new javax.swing.JLabel();
        txt_pcname = new javax.swing.JTextField();
        txt_ipaddress = new javax.swing.JTextField();
        btn_create = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        lbl_pcid = new javax.swing.JLabel();
        txt_pcid = new javax.swing.JTextField();
        lbl_backgroundaddpc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add PC");
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(400, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        lbl_heading.setFont(new java.awt.Font("Adobe Caslon Pro", 2, 36)); // NOI18N
        lbl_heading.setForeground(new java.awt.Color(255, 255, 255));
        lbl_heading.setText("Create PC...");
        getContentPane().add(lbl_heading);
        lbl_heading.setBounds(100, 10, 200, 40);

        lbl_pcname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_pcname.setForeground(new java.awt.Color(255, 255, 255));
        lbl_pcname.setText("PC Name    :");
        getContentPane().add(lbl_pcname);
        lbl_pcname.setBounds(40, 150, 110, 30);

        lbl_note.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lbl_note.setForeground(new java.awt.Color(255, 255, 255));
        lbl_note.setText("Note :  Make sure to use static IPs for entier network.");
        getContentPane().add(lbl_note);
        lbl_note.setBounds(40, 190, 330, 30);

        lbl_ipaddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_ipaddress.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ipaddress.setText("IP Address :");
        getContentPane().add(lbl_ipaddress);
        lbl_ipaddress.setBounds(40, 240, 110, 30);
        getContentPane().add(txt_pcname);
        txt_pcname.setBounds(150, 150, 200, 30);
        txt_pcname.getAccessibleContext().setAccessibleName("");

        getContentPane().add(txt_ipaddress);
        txt_ipaddress.setBounds(150, 240, 200, 30);

        btn_create.setText("Create");
        btn_create.setToolTipText("create new profile for PC");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });
        getContentPane().add(btn_create);
        btn_create.setBounds(40, 330, 120, 30);

        btn_clear.setText("Clear");
        btn_clear.setToolTipText("clear all fields");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clear);
        btn_clear.setBounds(220, 330, 120, 30);

        lbl_pcid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_pcid.setForeground(new java.awt.Color(255, 255, 255));
        lbl_pcid.setText("PC ID          :");
        getContentPane().add(lbl_pcid);
        lbl_pcid.setBounds(40, 80, 110, 30);

        txt_pcid.setEditable(false);
        getContentPane().add(txt_pcid);
        txt_pcid.setBounds(150, 80, 200, 30);

        lbl_backgroundaddpc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Ashen_Cafe/view/BackgroundGameZone.jpg"))); // NOI18N
        lbl_backgroundaddpc.setText("Background");
        getContentPane().add(lbl_backgroundaddpc);
        lbl_backgroundaddpc.setBounds(0, 0, 400, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        Computer pc=new Computer();
        Terminal te=new Terminal();
        ProgressBar pb=new ProgressBar();
                
        DataBaseComputer db=new DataBaseComputer();
        DataBaseTerminal dbt=new DataBaseTerminal();
        DataBaseProgressBar dbp=new DataBaseProgressBar();
        
        Message msg=new Message();
        Validation vd=new Validation();
        
        pc.setId(id);
        pc.setPcName(txt_pcname.getText());
        pc.setIpAddress(txt_ipaddress.getText());
        
        te.setId(id);
        te.setPcname(txt_pcname.getText());
        te.setSystime("00:00:00");
        te.setDuration("0");
        te.setSysdate("1996:07:13");
        
        pb.setId(id);
        pb.setPvalue(0);
        pb.setTimeclosed("00:00:00");
        
   
        if(pc.getPcName().isEmpty())
            msg.warningMsg("PC Name shoud not be empty", this);
        else if(vd.isNumeric(pc.getPcName()))
            msg.warningMsg("PC Name should not be numeric", this); 
        else if(pc.getIpAddress().isEmpty())
            msg.warningMsg("IP Address should not be empty", this);
        else if(!vd.isIPAddress(pc.getIpAddress()))
            msg.warningMsg("Insert a correct IP Address", this);
        else{
            int dialogResult = msg.confirmMsg("Do you want to create a new PC ", this);
            if( dialogResult ==  0 ){
	try{

            db.insert(pc);
 
            dbt.insert(te);

            dbp.insert(pb);
            
          /*  System.out.println("PC id is :"+pc.getId());
            System.out.println("Terminal id is :"+te.getId());
            System.out.println("ProgressBar id is :"+pb.getId());*/
            
            menu.setTable();
            menu.setComputerTable();
            
            clearAll();
	    msg.informMsg("PC Successfully Created", this);	
	    this.dispose();	
                }
        catch(Exception ex){
	    msg.warningMsg("Error in AddPC Form"+"\n"+ex.toString(), this);
		}	
            }
        }
        
       
    }//GEN-LAST:event_btn_createActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        Message msg=new Message();
        
        int dialogResult = msg.confirmMsg("Do you want to clear all the fields? ", this);
				if(dialogResult ==  0){
					clearAll();
				}
    }//GEN-LAST:event_btn_clearActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DataBaseComputer db=new DataBaseComputer();
        Computer pc= new Computer();
        int lastID=db.searchRows();
        id=lastID+1;
        txt_pcid.setText(Integer.toString(id));
        System.out.println("id is"+id);
    }//GEN-LAST:event_formWindowOpened
    public void clearAll(){
        txt_pcname.setText("");
        txt_ipaddress.setText("");
    }
    /**
     * @param args the command line arguments
     */
    private int id;
    private MainMenu menu;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_create;
    private javax.swing.JLabel lbl_backgroundaddpc;
    private javax.swing.JLabel lbl_heading;
    private javax.swing.JLabel lbl_ipaddress;
    private javax.swing.JLabel lbl_note;
    private javax.swing.JLabel lbl_pcid;
    private javax.swing.JLabel lbl_pcname;
    private javax.swing.JTextField txt_ipaddress;
    private javax.swing.JTextField txt_pcid;
    private javax.swing.JTextField txt_pcname;
    // End of variables declaration//GEN-END:variables
}
