/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Ashen_Cafe.view;

import com.Ashen_Cafe.Support.GetRowCount;
import com.Ashen_Cafe.Support.Message;
import com.Ashen_Cafe.Support.PingPC;
import com.Ashen_Cafe.database.DataBaseConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.LinkedList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MaLindu DiLshan
 */
public class CheckStatus extends javax.swing.JFrame {

    /**
     *
     */
    public CheckStatus() {
        initComponents();         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_heading = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_status = new javax.swing.JTable();
        btn_ok = new javax.swing.JButton();
        lbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PCs Status Table");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbl_heading.setFont(new java.awt.Font("Adobe Caslon Pro", 2, 36)); // NOI18N
        lbl_heading.setForeground(new java.awt.Color(255, 255, 255));
        lbl_heading.setText("PCs Status...");

        tbl_status.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PC Name", "IP Address", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_status);
        if (tbl_status.getColumnModel().getColumnCount() > 0) {
            tbl_status.getColumnModel().getColumn(0).setResizable(false);
            tbl_status.getColumnModel().getColumn(1).setResizable(false);
            tbl_status.getColumnModel().getColumn(2).setResizable(false);
            tbl_status.getColumnModel().getColumn(3).setResizable(false);
        }

        btn_ok.setText("OK");
        btn_ok.setToolTipText("click here to close this window");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        lbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Ashen_Cafe/view/BackgroundGameZone.jpg"))); // NOI18N
        lbl_background.setText("Background");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbl_background, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(lbl_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbl_background, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbl_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Message msg=new Message();
    dtm = (DefaultTableModel) tbl_status.getModel();
    tbl_status.setPreferredScrollableViewportSize(tbl_status.getPreferredSize());
 
        try{    
   DataBaseConnection dbcon=new DataBaseConnection();
   con=dbcon.connection();
   Statement st=con.createStatement();
   status = "No Response";
   checkArray=new LinkedList();
				
ResultSet rs = st.executeQuery("select*from computers");				
    while(rs.next()){
        
        ping=new PingPC();
        ping.setThreadID(rs.getInt(1));
        ping.setPcname(rs.getString(2));
        ping.setIp(rs.getString(3));
        
        checkArray.add(ping);
        ping.start();
    }	
con.close();
}
catch(SQLException e){
		System.out.println("SQL Error in Check Status Form"+"\n"+e.getMessage());
            }
        
        GetRowCount grc=new GetRowCount();
        rows=grc.getRowCount("computers");
        
        new Thread(new Runnable() {
        public void run() {
                Object waiter = new Object();
                synchronized (waiter) {
                        try {
                            waiter.wait(3000);
                            for(int i=0;i<rows;i++)
                            { 
                                ping=(PingPC)checkArray.get(i);
                                Vector v = new Vector();
        
                                v.add((Object)ping.getThreadID());
                                v.add((Object)ping.getPcname());
                                v.add((Object)ping.getIp());
                                v.add((Object)ping.getStatus());
                                dtm.addRow(v);
                            }
                        } catch (InterruptedException ex) {
                            System.out.println("InterruptedException inside Thread in PingPC class :" + ex.getMessage());
                        } catch (Exception ex) {
                            System.out.println("Exception inside Thread in PingPC class :" + ex.getMessage());
                        }
                }
            }
    }).start();

    }//GEN-LAST:event_formWindowOpened

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_okActionPerformed

    /**
     * @param args the command line arguments
     */ 
    private Connection con;
    private LinkedList checkArray;
    private String status;
    private int rows;
    private PingPC ping;
    private DefaultTableModel dtm;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_heading;
    private javax.swing.JTable tbl_status;
    // End of variables declaration//GEN-END:variables
}
