/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Ashen_Cafe.view;

import com.Ashen_Cafe.database.DataBaseComputer;
import com.Ashen_Cafe.database.DataBaseConnection;
import com.Ashen_Cafe.database.DataBaseTerminal;
import com.Ashen_Cafe.entity.Computer;
import com.Ashen_Cafe.Support.Message;
import com.Ashen_Cafe.database.DataBaseProgressBar;
import com.Ashen_Cafe.entity.ProgressBar;
import com.Ashen_Cafe.entity.Terminal;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author MaLindu DiLshan
 */
public class DeletePC extends javax.swing.JFrame {

    /**
     *
     */
    public DeletePC() {
        initComponents();
    }
    
    public void setMenu(MainMenu menu){
        this.menu=menu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_heading = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        cmb_id = new javax.swing.JComboBox();
        lbl_pcname = new javax.swing.JLabel();
        txt_pcname = new javax.swing.JTextField();
        lbl_ipaddress = new javax.swing.JLabel();
        txt_ipaddress = new javax.swing.JTextField();
        btn_delete = new javax.swing.JButton();
        btn_cancle = new javax.swing.JButton();
        lbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Delete PC");
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(400, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        lbl_heading.setFont(new java.awt.Font("Adobe Caslon Pro", 2, 36)); // NOI18N
        lbl_heading.setForeground(new java.awt.Color(255, 255, 255));
        lbl_heading.setText("Remove PC...");
        getContentPane().add(lbl_heading);
        lbl_heading.setBounds(90, 10, 220, 40);

        lbl_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(255, 255, 255));
        lbl_id.setText("ID                 : ");
        getContentPane().add(lbl_id);
        lbl_id.setBounds(30, 80, 110, 30);

        cmb_id.setModel(new javax.swing.DefaultComboBoxModel());
        cmb_id.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_idItemStateChanged(evt);
            }
        });
        getContentPane().add(cmb_id);
        cmb_id.setBounds(140, 80, 210, 30);

        lbl_pcname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_pcname.setForeground(new java.awt.Color(255, 255, 255));
        lbl_pcname.setText("PC Name     :");
        getContentPane().add(lbl_pcname);
        lbl_pcname.setBounds(30, 140, 110, 30);

        txt_pcname.setEditable(false);
        getContentPane().add(txt_pcname);
        txt_pcname.setBounds(140, 140, 210, 30);

        lbl_ipaddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_ipaddress.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ipaddress.setText("IP Address :");
        getContentPane().add(lbl_ipaddress);
        lbl_ipaddress.setBounds(30, 210, 110, 30);

        txt_ipaddress.setEditable(false);
        getContentPane().add(txt_ipaddress);
        txt_ipaddress.setBounds(140, 210, 210, 30);

        btn_delete.setText("Delete");
        btn_delete.setToolTipText("click here to delete profile");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delete);
        btn_delete.setBounds(40, 320, 110, 30);

        btn_cancle.setText("Clear");
        btn_cancle.setToolTipText("clear all fields");
        btn_cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancleActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancle);
        btn_cancle.setBounds(240, 320, 110, 30);

        lbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Ashen_Cafe/view/BackgroundGameZone.jpg"))); // NOI18N
        lbl_background.setText("Background");
        getContentPane().add(lbl_background);
        lbl_background.setBounds(0, 0, 400, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        DataBaseComputer db=new DataBaseComputer();
        DataBaseTerminal dbt=new DataBaseTerminal();
        DataBaseProgressBar dbp=new DataBaseProgressBar();        
        
        Computer pc=new Computer();
        Terminal te=new Terminal();
        ProgressBar pb=new ProgressBar();
        
        Message msg=new Message();
 
        if(String.valueOf(cmb_id.getSelectedItem()).equals("Select ID"))
            msg.warningMsg("Computer ID should be selected", this);
        else{
            te=dbt.searchAll();
            int lastID = te.getId();
            
            id=Integer.parseInt(String.valueOf(cmb_id.getSelectedItem()));
            pc.setId(Integer.parseInt(String.valueOf(cmb_id.getSelectedItem())));
        int dialogResult = msg.confirmMsg("Do you want to delete this PC? ", this);
            if( dialogResult ==  0 ){
	try{
            if(id==0){
              msg.warningMsg("This record is does not exist...", this);
              clearAll();
            }
            else if(lastID!=id){
              msg.warningMsg("You can't Delete this record please start with the last record...", this);
              clearAll();
            }
            else{
                
            db.delete(id);
            dbt.delete(id);
            dbp.delete(id);
            
            menu.setTable();
            menu.setComputerTable();
            
            clearAll();
	    msg.informMsg("PC Successfully Deleted", this);	
	    this.dispose();	
                }
            }
        catch(Exception ex){
	    msg.warningMsg("Error in DeletePC Form"+"\n"+ex.toString(), this);
		}	
            }
        }    
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void cmb_idItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_idItemStateChanged
       Computer pc=new Computer();
       DataBaseComputer db=new DataBaseComputer();
       if(cmb_id.getSelectedItem().equals("Select ID"))
        {
            System.out.println("select id");
            txt_pcname.setText("");
            txt_ipaddress.setText("");
        }
       else{
          int id=Integer.parseInt(String.valueOf(cmb_id.getSelectedItem()));
          pc=db.search(id);
          pcname=pc.getPcName();
          txt_pcname.setText(pc.getPcName());
          txt_ipaddress.setText(pc.getIpAddress());
       }
    }//GEN-LAST:event_cmb_idItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
   DataBaseConnection dbcon=new DataBaseConnection();
   
   con=dbcon.connection();
   Statement st=con.createStatement();
				
ResultSet rs = st.executeQuery("select id from computers");				
cmb_id.addItem("Select ID");
while(rs.next()){											
cmb_id.addItem(rs.getInt(1));			
}	
con.close();
}
catch(SQLException e){
		System.out.println("SQL Error in DeletePC Form"+"\n"+e.getMessage());
            }
    }//GEN-LAST:event_formWindowOpened

    private void btn_cancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancleActionPerformed
            Message msg=new Message();
        int dialogResult = msg.confirmMsg("Do you want to clear all the fields? ", this);
				if(dialogResult ==  0){
					clearAll();
				}      
    }//GEN-LAST:event_btn_cancleActionPerformed
public void clearAll(){
    cmb_id.setSelectedItem("Select ID");
    txt_pcname.setText("");
    txt_ipaddress.setText("");
    
}
    /**
     * @param args the command line arguments
     */
    private Connection con;
    private int id;
    private MainMenu menu;
    private String pcname;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancle;
    private javax.swing.JButton btn_delete;
    private javax.swing.JComboBox cmb_id;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_heading;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_ipaddress;
    private javax.swing.JLabel lbl_pcname;
    private javax.swing.JTextField txt_ipaddress;
    private javax.swing.JTextField txt_pcname;
    // End of variables declaration//GEN-END:variables
}
