/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Ashen_Cafe.view.systemUserView;

import com.Ashen_Cafe.Support.Message;
import com.Ashen_Cafe.Support.Validation;
import com.Ashen_Cafe.database.DataBaseMembershipTime;
import com.Ashen_Cafe.database.DataBaseSystemUsers;
import com.Ashen_Cafe.entity.MembershipTime;
import com.Ashen_Cafe.entity.Systemusers;
import com.Ashen_Cafe.view.AddTime;
import com.Ashen_Cafe.view.MainMenu;
/**
 *
 * @author MaLindu DiLshan
 */
public class AssignCost extends javax.swing.JFrame {

    /*
     *
     */
    public AssignCost() {
        initComponents();
    }
    public void setMenuRef(MainMenu menu) {
        this.menu=menu;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_heading = new javax.swing.JLabel();
        lbl_currentamt = new javax.swing.JLabel();
        lbl_member = new javax.swing.JLabel();
        lbl_newamt = new javax.swing.JLabel();
        txt_guest = new javax.swing.JTextField();
        txt_member = new javax.swing.JTextField();
        btn_create = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        txt_amt = new javax.swing.JTextField();
        lbl_type = new javax.swing.JLabel();
        lbl_amtperhour = new javax.swing.JLabel();
        lbl_guest = new javax.swing.JLabel();
        jcb_type = new javax.swing.JComboBox();
        lbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Assign Cost Per Hour");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbl_heading.setFont(new java.awt.Font("Adobe Caslon Pro", 2, 36)); // NOI18N
        lbl_heading.setForeground(new java.awt.Color(255, 255, 255));
        lbl_heading.setText("Assign Cost Per Hour");

        lbl_currentamt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_currentamt.setForeground(new java.awt.Color(255, 255, 255));
        lbl_currentamt.setText("Current Amounts                :-");

        lbl_member.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_member.setForeground(new java.awt.Color(255, 255, 255));
        lbl_member.setText("Member                   :");

        lbl_newamt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_newamt.setForeground(new java.awt.Color(255, 255, 255));
        lbl_newamt.setText("Enter your new amounts   :-");

        txt_guest.setEditable(false);

        txt_member.setEditable(false);

        btn_create.setText("Update");
        btn_create.setToolTipText("click here to assign cost per hour");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });

        btn_clear.setText("Clear");
        btn_clear.setToolTipText("clear all fields");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        lbl_type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_type.setForeground(new java.awt.Color(255, 255, 255));
        lbl_type.setText("Person Type           :");

        lbl_amtperhour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_amtperhour.setForeground(new java.awt.Color(255, 255, 255));
        lbl_amtperhour.setText("Amount per hour  :");

        lbl_guest.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_guest.setForeground(new java.awt.Color(255, 255, 255));
        lbl_guest.setText("Guest                       :");

        jcb_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Type", "Guest", "Member" }));

        lbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Ashen_Cafe/view/systemUserView/BackgroundGameZon.jpg"))); // NOI18N
        lbl_background.setText("Background");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_guest, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_newamt, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jcb_type, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btn_create, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(txt_member, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_type, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(txt_guest, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lbl_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_amtperhour, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_currentamt, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_member, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(txt_amt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbl_background, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lbl_guest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(lbl_newamt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jcb_type, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(btn_create, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(txt_member, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(lbl_type, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(txt_guest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbl_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(lbl_amtperhour, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(lbl_currentamt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(lbl_member, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(txt_amt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbl_background, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        txt_guest.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        DataBaseMembershipTime dbm=new DataBaseMembershipTime();

        MembershipTime mem=new MembershipTime();
        Message msg=new Message();
        Validation vd=new Validation();
        
        if(String.valueOf(jcb_type.getSelectedItem()).equals("Select Type"))
            msg.warningMsg("Person type should be selected", this);
        else if(txt_amt.getText().equals(""))
            msg.warningMsg("Amount should not be empty", this);
        else if(!vd.isNumeric(txt_amt.getText()))
            msg.warningMsg("Amount should be numbers", this);
        else if(Integer.parseInt(txt_amt.getText())==0)
            msg.warningMsg("Enter valid amount", this);
        else{
            int dialogResult = msg.confirmMsg("Do you want to update amount? ", this);
            if( dialogResult ==  0 ){
              try{
        mem.setMembertype(String.valueOf(jcb_type.getSelectedItem()));
        mem.setCharge(Integer.parseInt(txt_amt.getText()));
        
                dbm.update(mem,mem.getMembertype());
                
                clearAll();
                msg.informMsg("Amounts Successfully Updated", this);
                this.dispose();
                        }
            catch(Exception ex){
                msg.warningMsg(ex.toString(), this);
                }
            }
        }
    }//GEN-LAST:event_btn_createActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
            Message msg=new Message();
        
        int dialogResult = msg.confirmMsg("Do you want to clear all the fields? ", this);
				if(dialogResult ==  0){
					clearAll();
				}
    }//GEN-LAST:event_btn_clearActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DataBaseMembershipTime dbm=new DataBaseMembershipTime();

        MembershipTime mem=new MembershipTime();
        mem=dbm.search("Guest");
        txt_guest.setText(Integer.toString(mem.getCharge()));
        
        mem=dbm.search("Member");
        txt_member.setText(Integer.toString(mem.getCharge()));
    }//GEN-LAST:event_formWindowOpened
    public void clearAll(){
        jcb_type.setSelectedItem("Select Type");
        txt_amt.setText("");
    }
    /**
     * @param args the command line arguments
     */
    private int id;
    private MainMenu menu;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_create;
    private javax.swing.JComboBox jcb_type;
    private javax.swing.JLabel lbl_amtperhour;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_currentamt;
    private javax.swing.JLabel lbl_guest;
    private javax.swing.JLabel lbl_heading;
    private javax.swing.JLabel lbl_member;
    private javax.swing.JLabel lbl_newamt;
    private javax.swing.JLabel lbl_type;
    private javax.swing.JTextField txt_amt;
    private javax.swing.JTextField txt_guest;
    private javax.swing.JTextField txt_member;
    // End of variables declaration//GEN-END:variables
}
